name: animations
description: Custom Painters, controllers e wrappers de animacao reutilizaveis.
publish_to: none
version: 0.0.1

environment:
  sdk: ">=3.10.0-0 <4.0.0"

resolution: workspace

dependencies:
  core:
    path: ../core
  design_system:
    path: ../design_system
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
