name: landing
description: Landing page de Jose Guilherme Alves - Flutter Developer
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.10.0-0 <4.0.0"

resolution: workspace

dependencies:
  animations:
    path: ../../packages/animations
  core:
    path: ../../packages/core
  cupertino_icons: ^1.0.8
  design_system:
    path: ../../packages/design_system
  feature_about:
    path: ../../packages/feature_about
  feature_contact:
    path: ../../packages/feature_contact
  feature_hero:
    path: ../../packages/feature_hero
  feature_labs:
    path: ../../packages/feature_labs
  feature_services:
    path: ../../packages/feature_services
  feature_showcase:
    path: ../../packages/feature_showcase
  feature_tech:
    path: ../../packages/feature_tech
  flutter:
    sdk: flutter
  go_router: ^16.2.4
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
